spring:
  datasource:
    url: jdbc:h2:file:./data/jumpbeat;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: INFO
